# Uncomment the next line to define a global platform for your project
 platform :ios, '11.2'

target 'PixelsRock' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for PixelsRock
  pod 'EFColorPicker'

  target 'PixelsRockTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'PixelsRockUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
